### ISSUE TITLE
[2022.03.24(목요일)] Programmers(81302) : 거리두기 확인하기

### ISSUE THREAD

**Issue by ak2j38** [CodeSquad-Algorithm/Algorithm#69]
## 문제링크
[거리두기 확인하기](https://programmers.co.kr/learn/courses/30/lessons/81302?language=java)

## 난이도
프로그래머스 기준 Lv.2 입니다!

**Comment by seyoung755** [comment]
카카오 인턴십 기출이군요..!

**Comment by ak2j38** [comment]
아니.... 선생님들은 카카오 기출문제를 이미 경험하셨군요 ㅋㅋㅋㅋㅋㅋㅋㅋ
