### ISSUE TITLE
[2022.03.31(목)] Programmers(72413): 합승 택시 요금 

### ISSUE THREAD

**Issue by seyoung755** [CodeSquad-Algorithm/Algorithm#86]
## 문제링크
https://programmers.co.kr/learn/courses/30/lessons/72413

## 난이도
프로그래머스 lv.3 

이번주 주제와 어울리는 기출문제를 하나 준비해봤습니다

**Comment by ak2j38** [comment]
카카오 블라인드 기출문제군요!
